{
 "title": "Nifi Dashboard",
 "description": "Dashboard for PrometheusReportingTask metrics + JVM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Amount bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(nifi_amount_bytes_read)", "legendFormat": "read" },
    {
     "expr": "sum(nifi_amount_bytes_received)",
     "legendFormat": "received"
    },
    { "expr": "sum(nifi_amount_bytes_sent)", "legendFormat": "sent" },
    {
     "expr": "sum(nifi_amount_bytes_transferred)",
     "legendFormat": "transferred"
    },
    { "expr": "sum(nifi_amount_bytes_written)", "legendFormat": "written" }
   ]
  },
  {
   "title": "Flowfiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nifi_amount_flowfiles_received)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(nifi_amount_flowfiles_removed)",
     "legendFormat": "removed"
    },
    {
     "expr": "sum(nifi_amount_flowfiles_sent)",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(nifi_amount_flowfiles_transferred)",
     "legendFormat": "transferred"
    }
   ]
  },
  {
   "title": "Items",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nifi_amount_items_input)", "legendFormat": "input" },
    { "expr": "sum(nifi_amount_items_output)", "legendFormat": "output" },
    { "expr": "sum(nifi_amount_items_queued)", "legendFormat": "queued" }
   ]
  },
  {
   "title": "Content size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(nifi_size_content_input_total)",
     "legendFormat": "input"
    },
    {
     "expr": "sum(nifi_size_content_output_total)",
     "legendFormat": "output"
    },
    {
     "expr": "sum(nifi_size_content_queued_total)",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nifi_backpressure_bytes_threshold)",
     "legendFormat": "bytes threshold"
    },
    {
     "expr": "avg(nifi_backpressure_object_threshold)",
     "legendFormat": "object threshold"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nifi_amount_threads_active)",
     "legendFormat": "active"
    },
    {
     "expr": "sum(nifi_amount_threads_terminated)",
     "legendFormat": "terminated"
    }
   ]
  },
  {
   "title": "JVM basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nifi_jvm_daemon_thread_count)",
     "legendFormat": "daemon_thread_count"
    },
    {
     "expr": "sum(nifi_jvm_file_descriptor_usage)",
     "legendFormat": "file_descriptor_usage"
    },
    { "expr": "sum(nifi_jvm_thread_count)", "legendFormat": "thread_count" }
   ]
  },
  {
   "title": "JVM heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(nifi_jvm_heap_non_usage)", "legendFormat": "non usage" },
    { "expr": "sum(nifi_jvm_heap_usage)", "legendFormat": "usage" },
    { "expr": "sum(nifi_jvm_heap_used)", "legendFormat": "used" }
   ]
  },
  {
   "title": "Transmitting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nifi_transmitting)", "legendFormat": "transmitting" }
   ]
  },
  {
   "title": "Average lineage duration",
   "type": "graph",
   "description": "The average lineage duration (in milliseconds) for all flow file processed by this component",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(nifi_average_lineage_duration)",
     "legendFormat": "ms"
    }
   ]
  }
 ]
}